config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  
  resources :itineraries
  resources :lists
  resources :notes
  resources :expense_trackers
  resources :users

  get "home", to:"home#index", as: :home
  get "about", to:"about#index", as: :about
  get "lists", to:"lists#index"
  get "notes", to: "notes#index"
  get "expense_trackers", to: "expense_trackers#index"
  get "map", to: "map#index"
  get 'weather', to:"weather#index"
  get "convert_currency", to: "currency_converter#convert"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get '/admin/dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'

  get '/admin/view_all_users', to: 'admin_dashboard#view_all_users', as: 'view_all_users'


  delete "logout", to: "sessions#destroy"

  root to: "home#index"

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_dashboard.rb
class AdminDashboard < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/expense_tracker.rb
class ExpenseTracker < ApplicationRecord
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
    has_many :expense_trackers, class_name: "ExpenseTracker", dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :workspace
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :workspace
end

app/models/user.rb
# this user model has the following fields in the database:
# - email:string
# - password_digest:string
# 
# the command 'has_secure_password' also adds the virtual attributes:
# - password:string (virtual)
# - password_confirmation:string (virtual)
#
# essentially, this means that we will never set with the password_digest field ourselves,
# the two virtual attributes will deal with it internally

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Input in the email field must be a valid email address."}
    validates :email, uniqueness: { message: "You already have an account" }

end

app/models/workspace.rb
class Workspace < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  has_many :lists, dependent: :destroy

  { public_visibility: 0, private_visibility: 1 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash[:notice] = "Logged in successfully."
    flash[:alert] = "Invalid email or password."
  end 
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :set_itinerary, only: %i[ show edit update destroy ]

  # GET /itineraries or /itineraries.json
  def index
    @itineraries = Itinerary.all
    @itineraries = Itinerary.order(datetime: :asc)
  end

  # GET /itineraries/1 or /itineraries/1.json
  def show
  end

  # GET /itineraries/new
  def new
    @itinerary = Itinerary.new
  end

  # GET /itineraries/1/edit
  def edit
  end

  # POST /itineraries or /itineraries.json
  def create
    @itinerary = Itinerary.new(itinerary_params)

    respond_to do |format|
      if @itinerary.save
        format.html { redirect_to itinerary_url(@itinerary), notice: "Itinerary was successfully created." }
        format.json { render :show, status: :created, location: @itinerary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itineraries/1 or /itineraries/1.json
  def update
    respond_to do |format|
      if @itinerary.update(itinerary_params)
        format.html { redirect_to itinerary_url(@itinerary), notice: "Itinerary was successfully updated." }
        format.json { render :show, status: :ok, location: @itinerary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itineraries/1 or /itineraries/1.json
  def destroy
    @itinerary.destroy

    respond_to do |format|
      format.html { redirect_to itineraries_url, notice: "Itinerary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itinerary
      @itinerary = Itinerary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def itinerary_params
      params.require(:itinerary).permit(:description, :location, :datetime)
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/itineraries/_form.html.erb
<%= form_with(model: itinerary) do |form| %>
  <% if itinerary.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(itinerary.errors.count, "error") %> prohibited this itinerary from being saved:</h2>

      <ul>
        <% itinerary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :datetime, style: "display: block" %>
    <%= form.datetime_field :datetime %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/itineraries/_itinerary.html.erb
<div id="<%= dom_id itinerary %>">
  <p>
    <strong>Description:</strong>
    <%= itinerary.description %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= itinerary.location %>
  </p>

  <p>
    <strong>Datetime:</strong>
    <%= itinerary.datetime %>
  </p>

</div>

app/views/itineraries/edit.html.erb
<h1>Editing itinerary</h1>

<%= render "form", itinerary: @itinerary %>

<br>

<div>
  <%= link_to "Show this itinerary", @itinerary %> |
  <%= link_to "Back to itineraries", itineraries_path %>
</div>

app/views/itineraries/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex align-items-center justify-content-center">
    <h1 class="title">My Itinerary</h1> 
</div>

<table class="table">
  <thead>
    <tr>
      <th>Event</th>
      <th>Location</th>
      <th>Date & Time</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @itineraries.each do |itinerary| %>
      <tr>
        <td><%= link_to itinerary.description, edit_itinerary_path(itinerary) %></td>
        <td><%= itinerary.location %></td>
        <td><%= itinerary.datetime %></td>
        <td>
          <%= link_to 'Delete', itinerary, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure you want to delete this item?' } %></td>
        <td>
      <tr>
    <% end %>
  </tbody>
</table>


<%= link_to "Add new itinerary item", new_itinerary_path %>

app/views/itineraries/new.html.erb
<h1>New itinerary</h1>

<%= render "form", itinerary: @itinerary %>

<br>

<div>
  <%= link_to "Back to itineraries", itineraries_path %>
</div>

app/views/itineraries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @itinerary %>

<div>
  <%= link_to "Edit this itinerary", edit_itinerary_path(@itinerary) %> |
  <%= link_to "Back to itineraries", itineraries_path %>

  <%= button_to "Destroy this itinerary", @itinerary, method: :delete %>
</div>