config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  
  resources :itineraries
  resources :lists
  resources :notes
  resources :expense_trackers
  resources :users

  get "home", to:"home#index", as: :home
  get "about", to:"about#index", as: :about
  get "lists", to:"lists#index"
  get "notes", to: "notes#index"
  get "expense_trackers", to: "expense_trackers#index"
  get "map", to: "map#index"
  get 'weather', to:"weather#index"
  get "convert_currency", to: "currency_converter#convert"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get '/admin/dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'

  get '/admin/view_all_users', to: 'admin_dashboard#view_all_users', as: 'view_all_users'


  delete "logout", to: "sessions#destroy"

  root to: "home#index"

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_dashboard.rb
class AdminDashboard < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/expense_tracker.rb
class ExpenseTracker < ApplicationRecord
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
    has_many :expense_trackers, class_name: "ExpenseTracker", dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :workspace
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :workspace
end

app/models/user.rb
# this user model has the following fields in the database:
# - email:string
# - password_digest:string
# 
# the command 'has_secure_password' also adds the virtual attributes:
# - password:string (virtual)
# - password_confirmation:string (virtual)
#
# essentially, this means that we will never set with the password_digest field ourselves,
# the two virtual attributes will deal with it internally

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Input in the email field must be a valid email address."}
    validates :email, uniqueness: { message: "You already have an account" }

end

app/models/workspace.rb
class Workspace < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  has_many :lists, dependent: :destroy

  { public_visibility: 0, private_visibility: 1 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash[:notice] = "Logged in successfully."
    flash[:alert] = "Invalid email or password."
  end 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_workspace, only: [:index, :new, :create, :destroy]
  before_action :set_list, only: %i[ show edit update destroy ]

  def set_workspace
    @workspace = Workspace.find(params[:workspace_id])
  end
  
  # GET /lists or /lists.json
  def index
    @lists = @workspace.lists
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = @workspace.lists.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = @workspace.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to workspace_lists_path(@workspace), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to workspace_lists_path(@workspace), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to workspace_lists_path(@workspace), notice: "List was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/lists/_form.html.erb
<%= form_with model: [@workspace, @list] do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Description:</strong>
    <%= list.description %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= list.completed %>
  </p>

</div>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", workspace_list_path(@workspace, @list) %> |
  <%= link_to "Back to lists", workspace_lists_path(@workspace) %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex align-items-center justify-content-center">
    <h1 class="title">My List</h1> 
</div>

<table class="table">
  <thead>
    <tr>
      <th>To-Do:</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <% if list.completed %>
        <tr class="table-secondary">
          <td class="striker"><%= link_to list.description, edit_list_path(list) %></td>
          <td>
            <center>
              <%= form_for(list) do |f| %>
              <%= f.text_field :description, type: 'hidden' %>
              <%= f.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
              <%= f.submit "Unmark as Complete", class: 'btn btn-outline-secondary btn-sm' %>
              <% end%>
            </center>
          </td>
          <td><%= link_to 'Delete', list, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure you want to delete this item?' } %></td>
        </tr>
      <% else %>
        <tr>
          <td><%= link_to list.description, edit_list_path(list) %></td>
          <td>
            <center>
              <%= form_for(list) do |f| %>
              <%= f.text_field :description, type: 'hidden' %>
              <%= f.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
              <%= f.submit "Mark as Complete", class: 'btn btn-outline-secondary btn-sm' %>
              <% end%>
            </center>
          </td>
          <td><%= link_to 'Delete', list, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure you want to delete this item?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


<%= link_to "Add new list item", new_list_path %>

app/views/lists/new.html.erb
<h1>Add new list item</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to list", workspace_lists_path(@workspace) %>
</div>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @list %>

<div>
  <%= link_to "Edit this list", edit_workspace_lists_path(@workspace, @list) %> |
  <%= link_to "Back to list", workspace_lists_path(@workspace) %>

  <%= button_to "Delete this list", [@workspace, @list], method: :delete %>
</div>