config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  
  resources :itineraries
  resources :lists
  resources :notes
  resources :expense_trackers
  resources :users

  get "home", to:"home#index", as: :home
  get "about", to:"about#index", as: :about
  get "lists", to:"lists#index"
  get "notes", to: "notes#index"
  get "expense_trackers", to: "expense_trackers#index"
  get "map", to: "map#index"
  get 'weather', to:"weather#index"
  get "convert_currency", to: "currency_converter#convert"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get '/admin/dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'

  get '/admin/view_all_users', to: 'admin_dashboard#view_all_users', as: 'view_all_users'


  delete "logout", to: "sessions#destroy"

  root to: "home#index"

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_dashboard.rb
class AdminDashboard < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/expense_tracker.rb
class ExpenseTracker < ApplicationRecord
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
    has_many :expense_trackers, class_name: "ExpenseTracker", dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :workspace
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :workspace
end

app/models/user.rb
# this user model has the following fields in the database:
# - email:string
# - password_digest:string
# 
# the command 'has_secure_password' also adds the virtual attributes:
# - password:string (virtual)
# - password_confirmation:string (virtual)
#
# essentially, this means that we will never set with the password_digest field ourselves,
# the two virtual attributes will deal with it internally

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Input in the email field must be a valid email address."}
    validates :email, uniqueness: { message: "You already have an account" }

end

app/models/workspace.rb
class Workspace < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  has_many :lists, dependent: :destroy

  { public_visibility: 0, private_visibility: 1 }
end

app/controllers/map_controller.rb
class MapController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to home_path, class: "navbar-brand" do %>
    <%= image_tag('tripmate-logo.png', alt: 'TripMate logo', size: "200x200") %>
  <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <% if Current.user %>
        <li class="nav-item">
          <%= link_to "List", lists_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Notes", notes_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Itinerary", itineraries_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Expense Tracker", expense_trackers_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Map", map_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Weather", weather_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Currency Converter", convert_currency_path, class:"nav-link"%>
        </li>
        
          <% if Current.user.admin == true %>
          <li class="nav-item">
          <%= link_to "Admin", users_path, class:"nav-link"%>
          </li>
          <%end%>
        <% end %>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item">
            <span class="navbar-text"><%= Current.user.email %><span>
        </li>
        <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Log In", sign_in_path, class:"nav-link"%>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>