config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  
  resources :itineraries
  resources :lists
  resources :notes
  resources :expense_trackers
  resources :users

  get "home", to:"home#index", as: :home
  get "about", to:"about#index", as: :about
  get "lists", to:"lists#index"
  get "notes", to: "notes#index"
  get "expense_trackers", to: "expense_trackers#index"
  get "map", to: "map#index"
  get 'weather', to:"weather#index"
  get "convert_currency", to: "currency_converter#convert"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get '/admin/dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'

  get '/admin/view_all_users', to: 'admin_dashboard#view_all_users', as: 'view_all_users'


  delete "logout", to: "sessions#destroy"

  root to: "home#index"

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_dashboard.rb
class AdminDashboard < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/expense_tracker.rb
class ExpenseTracker < ApplicationRecord
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
    has_many :expense_trackers, class_name: "ExpenseTracker", dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :workspace
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :workspace
end

app/models/user.rb
# this user model has the following fields in the database:
# - email:string
# - password_digest:string
# 
# the command 'has_secure_password' also adds the virtual attributes:
# - password:string (virtual)
# - password_confirmation:string (virtual)
#
# essentially, this means that we will never set with the password_digest field ourselves,
# the two virtual attributes will deal with it internally

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Input in the email field must be a valid email address."}
    validates :email, uniqueness: { message: "You already have an account" }

end

app/models/workspace.rb
class Workspace < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  has_many :lists, dependent: :destroy

  { public_visibility: 0, private_visibility: 1 }
end

app/controllers/expense_trackers_controller.rb
class ExpenseTrackersController < ApplicationController
    before_action :set_expense_lists_with_id, only: [:edit, :update, :destroy, :show]
    before_action :get_itinerary_tuple, only: [:new]

    def index
        @expense_lists = ExpenseTracker
        .joins("inner join itineraries on itineraries.id = expense_trackers.itinerary_id")
        .select("expense_trackers.id, expense_trackers.total_budget, expense_trackers.itinerary_id, expense_trackers.accommodation, expense_trackers.transportation, expense_trackers.meal, expense_trackers.other, itineraries.description")
        .order("expense_trackers.itinerary_id ASC")
    end

    def show
    end

    def new
        @expense_lists = ExpenseTracker.new
    end

    def edit
    end

    def update
        if @expense_lists.update(expense_params)
            redirect_to @expense_lists, notice: "The Expense Details were saved successfully."
        else
            render :edit
        end
    end

    def create
        @expense_lists = ExpenseTracker.new(expense_params)
        if @expense_lists.save
            redirect_to expense_trackers_path, notice: "The Expense Details were saved successfully."
        else
            render :new
        end
    end

    def destroy
        @expense_lists.destroy
        redirect_to expense_trackers_path, notice: "Successfully removed Expense ID #{@expense_lists.id}"
    end

    private
    def set_expense_lists_with_id
        @expense_lists = ExpenseTracker
        .joins("inner join itineraries on itineraries.id = expense_trackers.itinerary_id")
        .select("expense_trackers.id, expense_trackers.total_budget, expense_trackers.itinerary_id, expense_trackers.accommodation, expense_trackers.transportation, expense_trackers.meal, expense_trackers.other, itineraries.description")
        .order("expense_trackers.itinerary_id ASC").find(params[:id])
    end

    def get_itinerary_tuple
        @itineraries_tuple = Itinerary.all.select('id, description').order("id ASC")
    end

    def expense_params
        params.require(:expense_tracker).permit(:total_budget, :itinerary_id, :itinerary_description, :accommodation, :transportation, :meal, :other)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash[:notice] = "Logged in successfully."
    flash[:alert] = "Invalid email or password."
  end 
end

app/controllers/map_controller.rb
class MapController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/expense_trackers/_expense_list.html.erb
<% @expense_lists.each do |el| %>
    <tr>
        <td class="col-2" style="text-align: center"><%= el.itinerary_id %></td>
        <td class="col-3" style="text-align: center"><%= link_to el.description, expense_tracker_path(el) %></td>
        <td class="col-2" style="text-align: center"><%= el.id %></td>
        <td class="col-4"><div style="display: flex">
            <%= button_to " Show Details", expense_tracker_path(el), method: :get, class: "bi bi-eye btn btn-outline-success btn-sm" %> &nbsp
            <%= button_to " Edit", edit_expense_tracker_path(el), method: :get, class: "bi bi-pencil-square btn btn-outline-primary btn-sm" %> &nbsp
            <%= button_to " Delete", el, method: :delete, class: "bi bi-trash btn btn-outline-danger btn-sm" %>
        </div></td>
    </tr>
<% end %>

app/views/expense_trackers/_form.html.erb
<%= form_with model: @expense_lists do |form| %>
    
    <% if !@expense_lists.id %>
    <div class="mb-4">
        <%= form.label :itinerary_id, "This Expense is for:" %>
        <%= form.select :itinerary_id , @itineraries_tuple.pluck('id'), class: "form-control", prompt: 'Please select one...' %>
    </div>
    <% end %>

    <div class="mb-3">
        <%= form.label :total_budget, "My total budget for this trip is:" %>
        <div class="input-group mb-3">
            <span class="input-group-text">$</span>
            <%= form.number_field :total_budget, step: 0.01, class:"form-control", placeholder:"Amount"%>
        </div>
    </div>

    <div class="mb-3">
        <%= form.label :accommodation, "Accommodation:" %>
        <div class="input-group mb-3">
            <span class="input-group-text">$</span>
            <%= form.number_field :accommodation, step: 0.01, class:"form-control", placeholder:"Amount"%>
        </div>
    </div>

    <div class="mb-3">
        <%= form.label :transportation, "Transportation:" %>
        <div class="input-group mb-3">
            <span class="input-group-text">$</span>
            <%= form.number_field :transportation, step: 0.01, class:"form-control", placeholder:"Amount"%>
        </div>
    </div>

    <div class="mb-3">
        <%= form.label :meal, "Meal:" %>
        <div class="input-group mb-3">
            <span class="input-group-text">$</span>
            <%= form.number_field :meal, step: 0.01, class:"form-control", placeholder:"Amount"%>
        </div>
    </div>

    <div class="mb-3">
        <%= form.label :other, "Other:" %>
        <div class="input-group mb-3">
            <span class="input-group-text">$</span>
            <%= form.number_field :other, step: 0.01, class:"form-control", placeholder:"Amount"%>
        </div>
    </div>

    </br>
    <div class="mb-3">
        <div class="input-group">
            <i class="bi bi-check-lg btn btn-success" style="padding-right:0px"></i>
            <%= form.submit 'Save', class: "bi bi-backspace btn btn-success"%>
        </div>
    </div>
<% end %>


<script>

</script>

app/views/expense_trackers/edit.html.erb
<div>Expense Details</div>

<%= render "form", expense_lists: @expense_lists %>

<%= link_to " Back to Expense List", expense_trackers_path, class: "bi bi-backspace btn-secondary btn"%>

app/views/expense_trackers/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1 class="title ">My Expense Tracker</h1>     
</div>

<div><%= link_to "+ Add New Expense Details", new_expense_tracker_path, class: "btn btn-warning" %></div></br>
<div class="container">
  <div class="row">
    <div class="col-12" style="">
      <table class="table caption-top table-hover">
        <thead>
          <tr>
            <th style="text-align: center">Itinerary ID</th>
            <th style="text-align: center">Itinerary Name</th>
            <th style="text-align: center">Expense ID</th>
            <th style="text-align: center">Actions</th>
          </tr>
        </thead>
        <tbody>
        <% if @expense_lists.exists? %>
          <%= render "expense_list" %>
        <% else %>
          <tr style="text-align: center"><td>Sorry, there's no itinerary found...</td></tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/expense_trackers/new.html.erb
<div>Please fill in the Expense Details</div>

<%= render "form", expense_lists: @expense_lists %>

<div><%= link_to " Back to Expense List", expense_trackers_path, class: "bi bi-backspace btn btn-secondary btn"%></div>

app/views/expense_trackers/show.html.erb
<div>Expense Details</div>

<div>
    <div>My total budget for this trip is: </div>
        <%= number_to_currency(@expense_lists.total_budget)%>
    <div>Accommodations:</div>
        <%= number_to_currency(@expense_lists.accommodation)%>
    <div>Transportation:</div>
        <%= number_to_currency(@expense_lists.transportation)%>
    <div>Meal:</div>
        <%= number_to_currency(@expense_lists.meal)%>
    <div>Other:</div>
        <%= number_to_currency(@expense_lists.other)%>
    <div>My remaining budget:</div>
        <%= number_to_currency(@expense_lists.total_budget - @expense_lists.accommodation - @expense_lists.transportation - @expense_lists.meal - @expense_lists.other)%>
</div></br>

<div>
    <%= link_to " Edit this Expense", edit_expense_tracker_path(@expense_lists), class: "bi bi-pencil-square btn btn-primary btn" %> </br></br>
    <%= link_to " Back to Expense List", expense_trackers_path, class: "bi bi-backspace btn btn-secondary btn"%>
</div>